import os

SQLALCHEMY_DATABASE_URI = os.environ.get('SQLALCHEMY_DATABASE_URI')
SECRET_KEY = os.environ.get("SECRET_KEY")
BCRYPT_LOG_ROUNDS = os.environ.get("BCRYPT_LOG_ROUNDS", default=13)
JWT_ACCESS_LIFESPAN = {"hours": 24}
JWT_REFRESH_LIFESPAN = {"days": 30}
