"""empty message

Revision ID: bd3aeb0f689c
Revises: 4d28e4be9de0
Create Date: 2023-05-30 13:43:49.976384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd3aeb0f689c'
down_revision = '4d28e4be9de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_performer', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('registered_on', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('registered_on')
        batch_op.drop_column('is_performer')

    # ### end Alembic commands ###
